library(caret)
library(VIM)
library(ggplot2)
library(plyr)
library(multicore)
library(doMC)
library(stringr)
library(lubridate)
library(Cairo)                                        
library(scales)
library(xtable)
library(testthat)
##registerDoMC(2)
options(xtable.type = 'html')
options(xtable.include.rownames = FALSE)
set.seed(123)
options(stringsAsFactors = FALSE)
theme_set(theme_bw())